### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by thiagopbueno** [LIAMF-USP/liamf-page#1]
Pessoal, 

Criei um **gh-pages branch** para podermos acessar na web a página em construção...
Basta acessar [https://liamf-usp.github.io/liamf-page/](https://liamf-usp.github.io/liamf-page/)

[]s

**Comment by alan-barzilay** [comment]
hj em dia essa eh a branch principal, acho q podemo fechar esse issue e as outras 3 branches né
